---
- hosts: db
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: create file if doesn't exist
      file:
        state: touch
        path: /var/www/html/index.html
    - name: if line not there then add it
      lineinfile:
        state: present
        dest: /var/www/html/index.html
        line: Hostname={{ansible_hostname}}
    - name: restart apache
      service:
        name: httpd
        state: reloaded
        enabled: yes

