---
- hosts: db
  tasks:
    - name: create file if doesn't exist
      file:
        state: touch
        path: /home/ansible/hostname.conf
    - name: if line not there then add it
      lineinfile:
        state: present
        dest: /home/ansible/hostname.conf
        line: Hostname={{ansible_hostname}}

